# Generated by Django 5.2.12 on 2026-03-09 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_post_video_story_video_alter_story_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='messages/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
