# Generated by Django 5.2.12 on 2026-03-09 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_message_image_alter_message_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='story',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
