from django.urls import path
from . import views

urlpatterns = [

path('home/',views.home,name='home'),
path('explore/',views.search,name='explore'),
path('reels/',views.reels,name='reels'),
path('messages/',views.direct_messages,name='direct_messages'),
path('live/',views.live,name='live'),
path('post/',views.create_post,name='create_post'),
path('like/<int:post_id>/',views.like_post,name='like_post'),
path('follow/<int:user_id>/',views.follow_toggle,name='follow_toggle'),
path('api/follow/<int:user_id>/',views.follow_toggle,name='follow_toggle_api'),
path('search/',views.search,name='search'),
path('api/search/',views.search_api,name='search_api'),
path('notifications/',views.notifications,name='notifications'),
path('api/notifications/',views.notifications_api,name='notifications_api'),
path('api/notifications/mark-read/',views.notifications_mark_read,name='notifications_mark_read'),
path('api/like/<int:post_id>/',views.like_post,name='like_post_api'),
path('api/save/<int:post_id>/',views.save_post,name='save_post_api'),
path('api/post/create/',views.create_post,name='create_post_api'),
path('api/story/create/',views.create_story_api,name='create_story_api'),
path('api/reel/create/',views.create_reel_api,name='create_reel_api'),
path('api/post/<int:post_id>/',views.post_detail_api,name='post_detail_api'),
path('api/post/<int:post_id>/comment/',views.add_comment,name='add_comment_api'),
path('api/post/<int:post_id>/delete/',views.delete_post,name='delete_post_api'),
path('api/post/<int:post_id>/update/',views.update_post,name='update_post_api'),
path('api/profile/update/',views.profile_update_api,name='profile_update_api'),
path('api/user/<int:user_id>/followers/',views.user_followers_api,name='user_followers_api'),
path('api/user/<int:user_id>/following/',views.user_following_api,name='user_following_api'),
path('api/activity/stats/',views.activity_stats_api,name='activity_stats_api'),
path('api/story/<int:story_id>/',views.story_detail_api,name='story_detail_api'),
path('api/story/<int:story_id>/view/',views.story_mark_viewed_api,name='story_mark_viewed_api'),
path('api/story/<int:story_id>/delete/',views.delete_story_api,name='delete_story_api'),
path('api/chat/send/',views.api_chat_send,name='api_chat_send'),
path('api/chat/upload-image/',views.api_chat_upload_image,name='api_chat_upload_image'),
path('api/chat/<int:user_id>/mark-read/',views.api_chat_mark_read,name='api_chat_mark_read'),
path('chat/<int:user_id>/',views.chat,name='chat'),
path('profile/edit/',views.edit_profile,name='edit_profile'),
path('settings/',views.user_settings,name='settings'),
path('activity/',views.user_activity,name='activity'),
path('saved/',views.saved_posts,name='saved_posts'),
path('dark-mode/toggle/',views.toggle_dark_mode,name='toggle_dark_mode'),
path('help/',views.help_center,name='help_center'),
path('profile/<str:username>/',views.profile,name='profile'),

]
